"""initial payments and outbox schema

Revision ID: 43f7740512c9
Revises: 
Create Date: 2026-10-05 16:31:49.890291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '43f7740512c9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('request_fingerprint', sa.CHAR(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('webhook_url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('webhook_event_id', sa.UUID(), nullable=True),
    sa.Column('webhook_status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('webhook_attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('webhook_last_error', sa.Text(), nullable=True),
    sa.CheckConstraint("currency IN ('RUB','USD','EUR')", name='ck_payments_currency'),
    sa.CheckConstraint("status IN ('pending','succeeded','failed')", name='ck_payments_status'),
    sa.CheckConstraint("webhook_status IN ('pending','delivered','failed')", name='ck_payments_webhook_status'),
    sa.CheckConstraint('amount > 0 AND amount <= 999999999.99', name='ck_payments_amount_range'),
    sa.CheckConstraint('char_length(description) <= 500', name='ck_payments_description_length'),
    sa.CheckConstraint('webhook_attempts >= 0', name='ck_payments_webhook_attempts'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_payments_created_at', 'payments', ['created_at'], unique=False)
    op.create_index('ix_payments_status_pending', 'payments', ['status'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    op.create_table('outbox',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_no', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('next_attempt_no', sa.Integer(), nullable=True),
    sa.Column('attempt_state', sa.Text(), server_default=sa.text("'idle'"), nullable=False),
    sa.Column('attempt_owner', sa.Text(), nullable=True),
    sa.Column('attempt_epoch', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('attempt_lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recoveries', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("attempt_state IN ('idle','open','awaiting_retry','completed')", name='ck_outbox_attempt_state'),
    sa.CheckConstraint('attempt_epoch >= 0', name='ck_outbox_attempt_epoch'),
    sa.CheckConstraint('attempt_no >= 0', name='ck_outbox_attempt_no'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id', 'event_type', name='uq_outbox_payment_event')
    )
    op.create_index('ix_outbox_created_at', 'outbox', ['created_at'], unique=False)
    op.create_index('ix_outbox_retry_due', 'outbox', ['next_attempt_at'], unique=False, postgresql_where=sa.text("attempt_state = 'awaiting_retry'"))
    op.create_index('ix_outbox_unpublished', 'outbox', ['created_at'], unique=False, postgresql_where=sa.text('published_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_outbox_unpublished', table_name='outbox', postgresql_where=sa.text('published_at IS NULL'))
    op.drop_index('ix_outbox_retry_due', table_name='outbox', postgresql_where=sa.text("attempt_state = 'awaiting_retry'"))
    op.drop_index('ix_outbox_created_at', table_name='outbox')
    op.drop_table('outbox')
    op.drop_index('ix_payments_status_pending', table_name='payments', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index('ix_payments_created_at', table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
